### PR TITLE
Updated for Factorio 2.0.

### PR DESCRIPTION
**Pull request by Synthlight**
- Updated for Factorio 2.0.
- Added compatibility with Space Age, a 4th tier of loaders/beltboxes will be added if Space Age is active.
- Turbo loaders/beltboxes are NOT localized in other langs, only Eng.
- Removed the 'low' graphics as `hr_version` as the low/high split has been removed from the game.
- Not everything tested, but made sure loaders/beltboxes work.
- Migrations untested. I wouldn't recommend using an old save in 2.0 in the first place.

PS: If you aren't interested in maintaining it anymore, let me know. I'd be happy to take over the mod. (Not sure if mod portal transfers are a thing or not.)
Either way, I'm not gonna upload it as a mod there till I hear back or there's silence for a week or something.

### CODE REVIEW

**Comment by shanemadden** [comment]
Thanks for the PR! I should have some time to get it tested out and released this weekend.

**Comment by daz96050** [comment]
Error while applying migration: Deadlock's Stacking Beltboxes & Compact Loaders: deadlock-beltboxes-loaders_2.0.2.lua

LuaTechnology doesn't contain key effects.
stack traceback:
	[C]: in function '__index'
	...oaders__/migrations/deadlock-beltboxes-loaders_2.0.2.lua:5: in main chunk

**Comment by daz96050** [comment]
Removing the migration files entirely seems to fix the issue, if it's a 2.0 save.

**Comment by Synthlight** [comment]
lol. That's what I mean by "migrations untested". It at least worked for saves made in 2.0 when increasing the version number. (Though the version was already way past the migration version so...)
Some of the tech names changed. You can check the changelog for 2.0.7 and ctrl+f the tech.

For `effects` here you'd:
`for _, effect in pairs(technology.effects) do` -> `for _, effect in pairs(technology.prototype.effects) do`

I hesitate to commit anything affecting migrations though since I've never looked into how they work.

**Comment by Synthlight** [comment]
> Thanks for the PR! I should have some time to get it tested out and released this weekend.

Poke. It's been two weeks. Not sure what's up on your end, but I'd like to get an updated version on the mod portal.

**Comment by shanemadden** [comment]
Sorry for the delay, aiming to try to get this done later today.

**Comment by shanemadden** [comment]
Thanks again! Should have this released shortly.

**Pull request merged**
